// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjYSeBhp-nzZDUrfe8BooYq2nMbkVZafY',
    appId: '1:81163366752:web:392aed47b96e01859dae05',
    messagingSenderId: '81163366752',
    projectId: 'francisconnect',
    authDomain: 'francisconnect.firebaseapp.com',
    storageBucket: 'francisconnect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0yT6HkcZQg36SXm7sM0Xm7RbB0SLBy_Y',
    appId: '1:81163366752:android:a9cbcab0a03a1d929dae05',
    messagingSenderId: '81163366752',
    projectId: 'francisconnect',
    storageBucket: 'francisconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAazETiGVrqf7B81wluEigRs-_8hNQaj38',
    appId: '1:81163366752:ios:bda6bdd2b23c6fee9dae05',
    messagingSenderId: '81163366752',
    projectId: 'francisconnect',
    storageBucket: 'francisconnect.firebasestorage.app',
    iosBundleId: 'com.example.francisconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAazETiGVrqf7B81wluEigRs-_8hNQaj38',
    appId: '1:81163366752:ios:bda6bdd2b23c6fee9dae05',
    messagingSenderId: '81163366752',
    projectId: 'francisconnect',
    storageBucket: 'francisconnect.firebasestorage.app',
    iosBundleId: 'com.example.francisconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjYSeBhp-nzZDUrfe8BooYq2nMbkVZafY',
    appId: '1:81163366752:web:9221b045997506279dae05',
    messagingSenderId: '81163366752',
    projectId: 'francisconnect',
    authDomain: 'francisconnect.firebaseapp.com',
    storageBucket: 'francisconnect.firebasestorage.app',
  );
}
